#!/usr/bin/env sh

alias vi='nvim'
alias  mkdir='mkdir -p'

alias  l='ls -1Ft --group-directories-first --color'
alias  la='ls -1FAt --group-directories-first --color'
alias  ll='ls -1FAlht --group-directories-first --color'
alias  lss='du -sh * | sort -h'

alias  mounted="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
alias  mounted_mac='mount | grep -E ^/dev | column -t'

#alias  grep='ag'

#alias  hist='history|grep'

alias  cpv='rsync -ah --info=progress2'
alias  dt='mv --force -t ~/.local/share/Trash'

# Shortcuts
alias config='cd ~/.config'
alias local='cd ~/.local'
alias dotfiles='cd ~/.local/share/dotfiles'
