#!/usr/bin/env sh

alias vi='nvim'
alias  mkdir='mkdir -p'

# ls 
# (used args)
# -l                        use a long listing format
# --color='always'          colorize the output;
# -a, --all                 do not ignore entries starting with .
# -A, --almost-all          do not list implied . and ..
# -h, --human-readable      with -l and -s, print sizes like 1K 234M 2G etc.
# --group-directories-first group directories before files;
# -t                        sort by modification time, newest first
# -r, --reverse             reverse order while sorting
alias  l='ls -1Ft --group-directories-first --color'
alias  la='ls -1FAt --group-directories-first --color'
alias ll='ls -lhrtF --group-directories-first --color'
alias  lss='du -sh * | sort -h'


alias  mounted="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
alias  mounted_mac='mount | grep -E ^/dev | column -t'

#alias  grep='ag'

#alias  hist='history|grep'

alias  cpv='rsync -ah --info=progress2'
alias  dt='mv --force -t ~/.local/share/Trash'

# Shortcuts
alias config='cd ~/.config'
alias local='cd ~/.local'
alias dotfiles='cd ~/.local/share/dotfiles'
