#!/usr/bin/env bash

exit

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link all files
for f in `find . -regex ".*\.vim$\|.*\.lua$"`; do
  rm -rf ~/.config/nvim/$f
  ln -s ~/dotfiles/awesome-streamerrc/ThePrimeagen/$f ~/.config/nvim/$f
done
